# Generated by Django 6.0.2 on 2026-04-28 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Кредиты')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Максимум студентов')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость курса (руб)')),
                ('duration_weeks', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Длительность курса (недели)')),
                ('prerequisites', models.TextField(blank=True, help_text='Что должен знать студент перед началом курса', verbose_name='Требования к слушателям')),
                ('certificate_available', models.BooleanField(default=True, verbose_name='Выдается сертификат')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('assistant', 'Ассистент'), ('teacher', 'Преподаватель'), ('senior_teacher', 'Старший преподаватель'), ('docent', 'Доцент'), ('professor', 'Профессор')], default='Преподаватель', max_length=100, verbose_name='Должность')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^EMP-\\d{6}$', 'Формат: EMP-123456')], verbose_name='Табельный номер')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(30000), django.core.validators.MaxValueValidator(500000)], verbose_name='Зарплата')),
                ('work_experience_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Общий стаж работы (лет)')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг преподавателя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^ST-\\d{6}$', 'Формат: ST-123456')], verbose_name='Студенческий билет №')),
                ('average_grade', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний балл')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителей')),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стипендия (руб)')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='schedule.course')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='schedule.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('assistant', 'Ассистент'), ('senior_lecturer', 'Старший преподаватель'), ('docent', 'Доцент'), ('professor', 'Профессор')], max_length=20, verbose_name='Ученая степень')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('office_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Лет опыта')),
                ('publications_count', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Количество публикаций')),
                ('scientific_degree_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)], verbose_name='Год получения ученой степени')),
                ('consulting_hours', models.CharField(blank=True, help_text='Например: Пн 14:00-16:00', max_length=50, verbose_name='Часы консультаций')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='schedule.teacher')),
            ],
            options={
                'verbose_name': 'Информация о преподавателе',
                'verbose_name_plural': 'Информация о преподавателях',
            },
        ),
    ]
